#!/usr/bin/env ruby

require File.expand_path("../../config/environment",  __FILE__)

users = [
  "Kermit", "Statler", "Waldorf", "Fozzie Bear", "Swedish Chef", "Beaker",
  "Animal", "Gonzo", "Dr. Bunsen Honeydew", "Rowlf", "Rizzo", "Miss Piggy",
  "Sam", "Floyd Pepper", "Dr. Teeth", "Janice", "Sweetums", "Pepe", "Camilla",
  "Crazy Harry", "Scooter", "Zoot", "Mahna Mahna", "Bobo", "Bean Bunny", "Lew Zealand"
]

$redis.multi
$redis.del("users")
users.each do |user|
  $redis.lpush("users", user)
end
$redis.exec
