#!/usr/bin/env ruby

require File.expand_path("../../config/environment",  __FILE__)

users = [
   "Richard Rodgers", "Helen Hayes", "Rita Moreno", "John Gielgud", "Audrey Hepburn",
   "Marvin Hamlisch", "Jonathan Tunick", "Mel Brooks", "Mike Nichols", "Whoopi Goldberg",
   "Scott Rudin"
]

$redis.multi
$redis.del("users")
users.each do |user|
  $redis.lpush("users", user)
end
$redis.exec
